# Generated by Django 5.0.2 on 2024-02-23 02:36

import licitaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Licitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('obs', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('close_date', models.DateTimeField()),
                ('status', models.CharField(choices=licitaciones.models.get_status, max_length=10)),
                ('currency', models.CharField(choices=licitaciones.models.get_currencies, max_length=15)),
                ('category', models.CharField(choices=licitaciones.models.get_categories, max_length=100)),
                ('method_payment', models.CharField(max_length=255)),
            ],
        ),
    ]
