# Generated by Django 5.0.2 on 2024-02-23 02:40

import licitaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licitacion',
            old_name='method_payment',
            new_name='payment_method',
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='status',
            field=models.CharField(choices=licitaciones.models.get_status, default='OPEN', max_length=10),
        ),
    ]
