# Generated by Django 5.0.2 on 2024-02-23 02:56

import licitaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0002_rename_method_payment_licitacion_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licitacion',
            name='city',
            field=models.CharField(blank=True, choices=licitaciones.models.get_cities, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='client',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
