# Generated by Django 5.0.2 on 2024-02-23 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0003_licitacion_city_licitacion_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licitacion',
            name='total_sum_lic',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LicitacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('note', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('licitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licitaciones.licitacion')),
            ],
        ),
    ]
