# Generated by Django 5.0.2 on 2024-03-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0004_licitacion_total_sum_lic_licitacionitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licitacion',
            name='close_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
