# Generated by Django 5.0.2 on 2024-03-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0005_alter_licitacion_close_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licitacion',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
