# Generated by Django 5.0.2 on 2024-04-05 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0006_alter_licitacion_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licitacionitem',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='licitacionitem',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
