# Generated by Django 5.0.2 on 2024-04-14 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0007_alter_licitacionitem_date_added_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licitacion',
            options={'verbose_name': 'licitacion', 'verbose_name_plural': 'licitaciones'},
        ),
    ]
