# Generated by Django 5.0.2 on 2024-05-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0008_alter_licitacion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licitacionitem',
            name='description',
            field=models.TextField(max_length=50),
        ),
    ]
