# Generated by Django 5.0.2 on 2024-12-27 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0009_alter_licitacionitem_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicitacionItemPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('licitacion_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licitaciones.licitacionitem')),
            ],
        ),
    ]
