# Generated by Django 5.0.2 on 2024-12-27 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0010_licitacionitemphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licitacionitemphoto',
            name='licitacion_item',
        ),
        migrations.AddField(
            model_name='licitacionitem',
            name='photos',
            field=models.ManyToManyField(to='licitaciones.licitacionitemphoto'),
        ),
        migrations.AddField(
            model_name='licitacionitemphoto',
            name='licitacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='licitaciones.licitacion'),
            preserve_default=False,
        ),
    ]
