# Generated by Django 5.0.2 on 2024-12-28 19:42

import django.db.models.deletion
import licitaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0012_alter_licitacionitem_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licitacionitem',
            name='photos',
        ),
        migrations.AddField(
            model_name='licitacionitemphoto',
            name='licitacion_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='licitaciones.licitacionitem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='licitacionitemphoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=licitaciones.models.user_path),
        ),
    ]
