# Generated by Django 5.0.2 on 2024-12-28 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0013_remove_licitacionitem_photos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licitacionitemphoto',
            name='licitacion',
        ),
    ]
