# Generated by Django 5.0.2 on 2024-12-28 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0016_remove_licitacionitemphoto_licitacion_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LicitacionItemPhoto',
        ),
    ]
