# Generated by Django 5.0.2 on 2024-12-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0018_licitacionitemphoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licitacionitemphoto',
            old_name='images',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='licitacionitemphoto',
            name='licitacion_item',
        ),
        migrations.AddField(
            model_name='licitacionitem',
            name='images',
            field=models.ManyToManyField(to='licitaciones.licitacionitemphoto'),
        ),
    ]
