# Generated by Django 5.0.2 on 2024-12-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0019_rename_images_licitacionitemphoto_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licitacionitem',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='licitaciones.licitacionitemphoto'),
        ),
    ]
