# Generated by Django 5.0.2 on 2024-02-23 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licitaciones', '0004_licitacion_total_sum_lic_licitacionitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum_offer', models.IntegerField()),
                ('total_items_submitted', models.IntegerField()),
                ('total_items_not_submitted', models.IntegerField()),
                ('payment_method', models.CharField(max_length=255)),
                ('delivery_time', models.CharField(blank=True, max_length=20, null=True)),
                ('licitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licitaciones.licitacion')),
            ],
        ),
        migrations.CreateModel(
            name='OfferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=10)),
                ('offer_price', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofertas.oferta')),
            ],
        ),
    ]
